#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("StudentHousing.Resource", IsApplication=true)]

namespace StudentHousing
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::StudentHousing.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::StudentHousing.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int common_google_signin_btn_text_dark = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int common_google_signin_btn_text_dark_default = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_google_signin_btn_text_dark_disabled = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_signin_btn_text_dark_focused = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_signin_btn_text_dark_pressed = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int common_google_signin_btn_text_light = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int common_google_signin_btn_text_light_default = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_signin_btn_text_light_disabled = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_signin_btn_text_light_focused = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_signin_btn_text_light_pressed = 2131034119;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ac = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blank_heart = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bookmarkButton = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bus = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_full_open_on_phone = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_disabled = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_dark_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_dark_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_disabled = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_focused = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_light_normal = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_light_pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_disabled = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_focused = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_dark_normal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_dark_pressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_disabled = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_focused = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_light_normal = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_light_pressed = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int dishwasher = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int furnished = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int heart = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_menu_moreoverflow_normal_holo_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int laundry = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int parking = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int petFriendly = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int property = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int stove = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int wheelChair = 2130837538;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080011
			public const int actionPenal = 2131230737;
			
			// aapt resource value: 0x7f08001e
			public const int address = 2131230750;
			
			// aapt resource value: 0x7f080013
			public const int addressInput = 2131230739;
			
			// aapt resource value: 0x7f080005
			public const int adjust_height = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int adjust_width = 2131230726;
			
			// aapt resource value: 0x7f080015
			public const int advancePanel = 2131230741;
			
			// aapt resource value: 0x7f080017
			public const int advanceSearchButton = 2131230743;
			
			// aapt resource value: 0x7f080027
			public const int amentities = 2131230759;
			
			// aapt resource value: 0x7f080026
			public const int amentityLabel = 2131230758;
			
			// aapt resource value: 0x7f08000a
			public const int auto = 2131230730;
			
			// aapt resource value: 0x7f08001d
			public const int bookmark = 2131230749;
			
			// aapt resource value: 0x7f08000e
			public const int bookmarks = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int bookmarsScroll = 2131230733;
			
			// aapt resource value: 0x7f08002f
			public const int btnCreateAcc = 2131230767;
			
			// aapt resource value: 0x7f08002d
			public const int btnLogin = 2131230765;
			
			// aapt resource value: 0x7f08000b
			public const int dark = 2131230731;
			
			// aapt resource value: 0x7f080025
			public const int description = 2131230757;
			
			// aapt resource value: 0x7f080024
			public const int descriptionLabel = 2131230756;
			
			// aapt resource value: 0x7f08000f
			public const int drawer_layout = 2131230735;
			
			// aapt resource value: 0x7f08002a
			public const int etEmail = 2131230762;
			
			// aapt resource value: 0x7f080031
			public const int etFName = 2131230769;
			
			// aapt resource value: 0x7f080033
			public const int etLName = 2131230771;
			
			// aapt resource value: 0x7f08002c
			public const int etPass = 2131230764;
			
			// aapt resource value: 0x7f080035
			public const int etPhone = 2131230773;
			
			// aapt resource value: 0x7f080014
			public const int goButton = 2131230740;
			
			// aapt resource value: 0x7f080000
			public const int hybrid = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int icon_only = 2131230727;
			
			// aapt resource value: 0x7f080019
			public const int left_drawer = 2131230745;
			
			// aapt resource value: 0x7f08000c
			public const int light = 2131230732;
			
			// aapt resource value: 0x7f08001b
			public const int linearLayout2 = 2131230747;
			
			// aapt resource value: 0x7f080010
			public const int linearLayout4 = 2131230736;
			
			// aapt resource value: 0x7f080018
			public const int map = 2131230744;
			
			// aapt resource value: 0x7f080012
			public const int menuButton = 2131230738;
			
			// aapt resource value: 0x7f080001
			public const int none = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int normal = 2131230722;
			
			// aapt resource value: 0x7f080028
			public const int notes = 2131230760;
			
			// aapt resource value: 0x7f080023
			public const int occupancyDate = 2131230755;
			
			// aapt resource value: 0x7f080022
			public const int occupancyDateLabel = 2131230754;
			
			// aapt resource value: 0x7f080020
			public const int priceLable = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int priceValue = 2131230753;
			
			// aapt resource value: 0x7f08001c
			public const int propertyMap = 2131230748;
			
			// aapt resource value: 0x7f080039
			public const int radioGroup1 = 2131230777;
			
			// aapt resource value: 0x7f08001f
			public const int ratingBar = 2131230751;
			
			// aapt resource value: 0x7f08003b
			public const int rbPoster = 2131230779;
			
			// aapt resource value: 0x7f08003a
			public const int rbRenter = 2131230778;
			
			// aapt resource value: 0x7f080003
			public const int satellite = 2131230723;
			
			// aapt resource value: 0x7f08001a
			public const int scrollView2 = 2131230746;
			
			// aapt resource value: 0x7f080016
			public const int space1 = 2131230742;
			
			// aapt resource value: 0x7f080008
			public const int standard = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int terrain = 2131230724;
			
			// aapt resource value: 0x7f080029
			public const int textView1 = 2131230761;
			
			// aapt resource value: 0x7f080036
			public const int textView10 = 2131230774;
			
			// aapt resource value: 0x7f080037
			public const int textView11 = 2131230775;
			
			// aapt resource value: 0x7f080038
			public const int textView12 = 2131230776;
			
			// aapt resource value: 0x7f08002b
			public const int textView2 = 2131230763;
			
			// aapt resource value: 0x7f08002e
			public const int textView3 = 2131230766;
			
			// aapt resource value: 0x7f080030
			public const int textView7 = 2131230768;
			
			// aapt resource value: 0x7f080032
			public const int textView8 = 2131230770;
			
			// aapt resource value: 0x7f080034
			public const int textView9 = 2131230772;
			
			// aapt resource value: 0x7f080009
			public const int wide = 2131230729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Bookmark = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int drawer_list_item = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Property = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int SignIn = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int SignUp = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060012
			public const int ApplicationName = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int Hello = 2131099665;
			
			// aapt resource value: 0x7f060015
			public const int StudentHousing = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int app_name = 2131099668;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_enable_button = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_enable_text = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_enable_title = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_button = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_text = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_install_title = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_notification_ticker = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_unknown_issue = 2131099664;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_unsupported_text = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_button = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_update_text = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_update_title = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_updating_text = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_wear_update_text = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int common_open_on_phone = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_signin_button_text = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int common_signin_button_text_long = 2131099663;
			
			// aapt resource value: 0x7f060016
			public const int google_maps_key = 2131099670;
			
			// aapt resource value: 0x7f060013
			public const int hello = 2131099667;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[]
			{
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
