#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("StudentHousing.Resource", IsApplication=true)]

namespace StudentHousing
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_menu_moreoverflow_normal_holo_light = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int actionPenal = 2131099649;
			
			// aapt resource value: 0x7f06000f
			public const int address = 2131099663;
			
			// aapt resource value: 0x7f060003
			public const int addressInput = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int advancePanel = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int advanceSearchButton = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int goButton = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout4 = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int map = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int menuButton = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int priceLable = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int priceValue = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int scrollView2 = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int space1 = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int tableLayout1 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int tableRow1 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int tableRow2 = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int tableRow3 = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int textView16 = 2131099664;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Property = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int StudentHousing = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int google_maps_key = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
